import tkinter as tk
from tkinter import messagebox
form=tk.Tk(className="Result")
form.minsize(500,500)
l=tk.Label(text="Quarter")
l.grid(row=0)
t=tk.Entry()
t.grid(row=0,column=1)
l1=tk.Label(text="Half")
l1.grid(row=0,column=2)
t1=tk.Entry()
t1.grid(row=0,column=3)
l2=tk.Label(text="Year")
l2.grid(row=0,column=4)
t2=tk.Entry()
t2.grid(row=0,column=5)
l3=tk.Label(text="Quarter")
l4=tk.Label(text="")
def changeText():
        l4.config(text=t.get())
        l6.config(text=t1.get())
        l8.config(text=t2.get())
        l10.config(text=int(t.get())+int(t1.get())+int(t2.get()))
button =tk.Button(text="Get_Result",command=changeText)
button.grid(row=5,column=3)
l4.grid(row=2,column=2)
l3.grid(row=2,column=1)
l5=tk.Label(text="half")
l6=tk.Label(text="")
l5.grid(row=3,column=1)
l6.grid(row=3,column=2)
l7=tk.Label(text="year")
l8=tk.Label(text="")
l7.grid(row=4,column=1)
l8.grid(row=4,column=2)
l9=tk.Label(text="total marks")
l10=tk.Label(text="")
l9.grid(row=3,column=3)
l10.grid(row=3,column=4)
form.mainloop()
