import tkinter as t
form=t.Tk(className="record")
form.minsize(500,500)
File=t.Menubutton(form,text="File")
File.grid(row=0)
File.menu=t.Menu(File)
File['menu']=File.menu
save=t.IntVar()
opn=t.IntVar()
def do():
    print("Saved")
    sv=t.Tk(className="Save As")
    sv.minsize(200,200)
    s1=t.Frame(sv)
    s1.grid(row=0)
    s2=t.Frame(sv)
    s2.grid(row=1)
    age=t.Spinbox(s2,from_=18,to=35)
    age.grid(row=3)
    age1=t.Spinbox(s1,from_=0,to=100)
    age.grid(row=4)
    age1.grid(row=5)
    sv.mainloop()
    form.quit()
File.menu.add_checkbutton(label="Save",variable=save,command=do)
File.menu.add_checkbutton(label="Open",variable=opn,command=do)
File.pack()
form.mainloop()
    
