import numpy as np
import matplotlib.pyplot as plt
x=np.array(["Anmol","Sushant","Arardhya","Aniket","Deepak"])
y=np.array([70,56,83,54,75])
'''plt.plot(x,np.sin(x),"y*")
plt.plot(x,np.cos(x),"b^")
plt.plot(x,np.tan(x),"r--")
plt.plot(x,x*2,"b")
plt.title("Graph")
plt.xlabel("x")
plt.ylabel("y")'''
z=np.array([40,85,62,45,87])
l=np.array([87,89,30,45,75])
m=np.array([52,56,72,98,20])
f,n=plt.subplots(2,2)
n[0][0].plot(x,y,"y--")
n[0][0].set_title("Maths")
n[0][1].plot(x,z,"b^")
n[0][1].set_title("English")
n[1][0].plot(x,l,"r*")
n[1][0].set_title("CSE")
n[1][1].plot(x,m,"g")
n[1][1].set_title("Science")
plt.show()
