import tkinter as t
form=t.Tk(className="MyForm")
form.minsize(500,1500)
File =t.Menubutton(form,text="FILE")
File.grid(row=0)
File.menu=t.Menu(File)
File["menu"]=File.menu
save=t.IntVar()
op=t.IntVar()
def do():
    print("save click")
    sv=t.Tk(className="Save as")
    sv.minsize(200,200)
    s1=t.Frame(sv,bg="red")
    s2=t.Frame(sv,bg="blue")
    age=t.Spinbox(s2,from_=18,to=35)
    age.grid(row=5)
    age1=t.Spinbox(s1,from_=0,to=100)
    age1.grid(column=2)
    s1.config(bg="cyan")
    s1.minsize(100,100)
    s2.grid(row=1)
    s1.grid(row=0)
    sv.mainloop()
    form.quit()
File.menu.add_checkbutton(label="SAve", variable=save,command=do)
File.menu.add_checkbutton(label="Open", variable=op)
File.pack()
form.mainloop()
