import tkinter as tk
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import mysql.connector
import re
from tkinter import *
def create():
    c=tk.Tk(className="Create DataBase")
    l1=tk.Label(c,text="Name of Database")
    l1.grid(row=1,column=0)
    e1=tk.Entry(c)
    e1.grid(row=1,column=1)
    def run():
        db=e1.get()
        con=mysql.connector.connect(host="localhost",user="root",passwd="")
        m=con.cursor()
        m.execute('create database %s'%db)
        con.commit()
        l1111=tk.Label(c,text='database created')
        l1111.grid(row=2,column=1)
    def entry():
        li=[]
        t=e3.get()
        st=e4.get()
        db=e1.get()
        con=mysql.connector.connect(host="localhost",user="root",passwd="",database=db)
        m=con.cursor()
        m.execute("create table %s (%s);"%(t,st))
        con.commit()
    def en():
            t=e3.get()
            st=e5.get()
            db=e1.get()
            con=mysql.connector.connect(host="localhost",user="root",passwd="",database=db)
            m=con.cursor()
            m.execute("insert into %s values (%s);"%(t,st))
            con.commit()
    btn9=tk.Button(c,text="do entry in table",command=en)
    btn9.grid(row=6,column=2)
    btn1=tk.Button(c,text="Create DB",command=run)
    btn1.grid(row=2,column=0)
    l2=tk.Label(c,text='enter table name')
    l2.grid(row=3,column=0)
    e3=tk.Entry(c)
    e3.grid(row=3,column=1)
    l3=tk.Label(c,text='enter Fields seperated by comma in format')
    l3.grid(row=4,column=0)
    e4=tk.Entry(c,width="50")
    e4.grid(row=4,column=1)
    l4=tk.Label(c,text='enter Fields seperated by comma in format')
    l4.grid(row=5,column=0)
    e5=tk.Entry(c,width="50")
    e5.grid(row=5,column=1)
    btn6=tk.Button(c,text="Do Entries",command=entry)
    btn6.grid(row=6,column=1)
def ret():
    g=tk.Tk(className="Retrieval")
    con=mysql.connector.connect(host="localhost",user="root",passwd="")
    m=con.cursor()
    m.execute('show databases')
    s=m.fetchall()
    lb=Listbox(g)
    lb.grid(row=1,column=0)
    lb.insert(END,*s)
    con.commit()
    lb1=Listbox(g)
    lb1.grid(row=1,column=1)
    txt=tk.Text(g)
    txt.grid(row=1,column=2)
    def showd():
        k=str(lb.get(ACTIVE))
        k=k.replace("'","")
        k=k.replace(",","")
        k=k.replace("(","")
        k=k.replace(")","")
        con=mysql.connector.connect(host="localhost",user="root",passwd="",database=k)
        m=con.cursor()
        m.execute('show full tables')
        s=m.fetchall()
        lb1.insert(END,*s)
        con.commit()
        print(g)
    def showt():
        k=str(lb.get(ACTIVE))
        k=k.replace("'","")
        k=k.replace(",","")
        k=k.replace("(","")
        k=k.replace(")","")
        j=lb1.get(ACTIVE)
        j=str(j[0])
        con=mysql.connector.connect(host="localhost",user="root",passwd="",database=k)
        m=con.cursor()
        m.execute('select * from %s'%j)
        s=m.fetchall()
        txt.insert("1.0",s)
        con.commit()
    btn7=tk.Button(g,text="See DataBase detail",command=showd)
    btn7.grid(row=2,column=0)
    btn8=tk.Button(g,text="See Table detail",command=showt)
    btn8.grid(row=2,column=1)
f=tk.Tk(className="Form")
btn1=tk.Button(text="Create",command=create)
btn1.grid(row=1,column=0)
btn2=tk.Button(text="Retrieve",command=ret)
btn2.grid(row=1,column=1)
btn3=tk.Button(text="Update")
btn3.grid(row=1,column=2)
btn4=tk.Button(text="Delete")
btn4.grid(row=1,column=3)
f.mainloop()
